name: Tests

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11"]
    steps:
      - name: Install libGLU library on Ubuntu
        run: |
            if [ "$RUNNER_OS" == "Linux" ]; then
                sudo apt-get install -y libglu1-mesa
            fi
        shell: bash
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and any other packages
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Run tox
        run: tox
